### ISSUE TITLE
[FABRIC 1.18.2 - CRASH] Bewitchment crops not compatible with Greenhouse?

### ISSUE THREAD

**Issue by MSandro** [Dalarion/Croparia#22]
Fabric Loader: 0.14.10
Fabric API: 0.67.0
Croparia: 3.8.3
Bewitchment: 1.18-23
```
[19:03:09] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
    at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:911) ~[server-intermediary.jar:?]
    at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:322) ~[?:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
    at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot set property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{bewitchment:garlic}
    at net.minecraft.state.State.with(State:117) ~[?:?]
    at com.croparia.mod.blockEntity.GreenhouseBE.tick(GreenhouseBE.java:51) ~[%5BFABRIC%5D-Croparia-3.8.3-1.18.2.jar:?]
    at com.croparia.mod.block.Greenhouse.lambda$getTicker$0(Greenhouse.java:93) ~[%5BFABRIC%5D-Croparia-3.8.3-1.18.2.jar:?]
    at net.minecraft.world.chunk.WorldChunk$DirectBlockEntityTickInvoker.tick(WorldChunk:659) ~[?:?]
    at net.minecraft.world.chunk.WorldChunk$WrappedBlockEntityTickInvoker.tick(WorldChunk:713) ~[?:?]
    at net.minecraft.world.World.redirect$fod000$redirectTick(World:9617) ~[?:?]
    at net.minecraft.world.World.tickBlockEntities(World:475) ~[?:?]
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld:368) ~[?:?]
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907) ~[server-intermediary.jar:?]
    ... 5 more
```

**Comment by MSandro** [comment]
MoriyaShiine:
> This is on Croparia, it assumes all crops that aren't Beetroot have the same age property. https://github.com/Dalarion/Croparia/blob/master/src/main/java/com/croparia/mod/common/blockEntity/GreenHouseBE.java#L49
> 
> Luckily this is fixable on their end by getting the CropBlock's age property (with CropBlock#getAgeProperty() in yarn) instead of _always_ the one for wheat and other non-beetroot blocks, and would fix crashes with any other mod that also uses different age properties

I hope you can fix this issue soon, thanks
