### ISSUE TITLE
[Fabric 1.19.2] Crash when trying to open Seed Recycler

### ISSUE THREAD

**Issue by NitroxydeX** [Dalarion/Croparia#24]
When you try to open a Seed Recycler the server just crashes.

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2022-12-18 22:15:28
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at com.defacto34.croparia.client.screen.handlers.TransformerScreenHandler.<init>(TransformerScreenHandler.java:26)
	at com.defacto34.croparia.core.blockEntity.TransformerBE.createMenu(TransformerBE.java:187)
	at net.minecraft.class_3222.method_17355(class_3222.java:1040)
	at com.defacto34.croparia.core.block.SeedRecycler.method_9534(SeedRecycler.java:34)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:964)
	at net.minecraft.class_3225.method_14262(class_3225.java:338)
	at net.minecraft.class_3244.method_12046(class_3244.java:1145)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:menu / croparia:transformer])
	at net.minecraft.class_2370.method_40274(class_2370.java:81)
	at net.minecraft.class_2370.method_31051(class_2370.java:91)
	at net.minecraft.class_2370.method_10273(class_2370.java:87)
	at net.minecraft.class_2370.method_10272(class_2370.java:135)
	at net.minecraft.class_2378.method_39197(class_2378.java:508)
	at net.minecraft.class_2378.method_10230(class_2378.java:504)
	at net.fabricmc.fabric.api.screenhandler.v1.ScreenHandlerRegistry.registerSimple(ScreenHandlerRegistry.java:90)
	at com.defacto34.croparia.client.screen.ModScreenHandlers.<clinit>(ModScreenHandlers.java:14)
	... 23 more
```

**Comment by LieutenantCrunch** [comment]
Have the same issue (`[FABRIC] Croparia-4.0.1 MC 1.19.2`)
